### ISSUE TITLE
Questions about License

### ISSUE THREAD

**Issue by besnoi** [petarov/game-off-2017#25]
This is not a feature-request or bug but an honest question!
> Are you allowed to use proprietary assets in your game and then bundle it as open-source?

**Doesn't that fall under "redistributing the assets" in some sense?**

Various public-domain assets make an exception stating that that doesn't include "bundling the assets as part of the game or open-source project" but I'm not sure if proprietary assets are licensed like that. For instance envato doesn't even allow HTML5 templates to be used as wordpress themes (both free and commercial)

Please reflect your thoughts on this!!

**Comment by n3tn0de** [comment]
Hi @YoungNeer !

The assets we purchased are under the Envanto `Regular License`.
Both Regular and Extended licenses permit product distribution with the assets incorporated:

https://help.market.envato.com/hc/en-us/articles/115005593363-Do-I-need-a-Regular-License-or-an-Extended-License-

`The main difference between these licenses is that under the Regular License, your end product (incorporating the item you've purchased) is distributed free of charge, whereas under the Extended License your end product may be sold or otherwise limited to paying customers.`

They have also some examples of use cases. 

And to be extra safe we only include generated spritesheet, not the original source (‘.psd’ file in this case).

**Comment by YoungNeer** [comment]
Thanks for replying. That clears the concept.
But I have some more questions if you will.
Lets' say I bought an envato UI pack - can I use them in my GUI library? (of-course the psd file won't be included)
